Humble
gbartyzel/ros2_net_ft_driver pull request #13
Opened 2023-10-04 09:32 UTC by tianjiawen1

2023-10-05 09:59 UTC, gbartyzel requested changes

2023-10-05 09:59 UTC, gbartyzel commented on net_ft_description/urdf/net_ft_sensor.urdf.xacro
> +    <xacro:arg name="ip_address" default="192.168.1.10" />
The default IP is `192.168.1.1`, so please, revert this :)

2023-10-05 09:59 UTC, gbartyzel commented on net_ft_driver/launch/net_ft_broadcaster.launch.py
> +            default_value="192.168.1.10",
Also, here

2023-10-05 09:59 UTC, gbartyzel commented on net_ft_driver/launch/net_ft_broadcaster.launch.py
> +            default_value="flase",
There is a typo: should be `false`

2023-10-16 08:28 UTC, gbartyzel commented
@tianjiawen1 Can you look at the comments?

2023-10-17 06:04 UTC, tianjiawen1 commented
> @tianjiawen1 Can you look at the comments?

yes，i tested on ati gamma ,it works.

2023-10-19 06:44 UTC, gbartyzel commented
@tianjiawen1 That's great, but please change the default IP address to 192.168.1.1 (it's the default for ATI AXIA and more)

2023-10-26 17:29 UTC, gbartyzel commented
Fix introduced in #14. Closing PR/

2023-10-26 17:29 UTC, closed without merging